### ISSUE TITLE
Location of exporting degree status to CSV logic - fe / be?

### ISSUE THREAD

**Issue by benny-n** [sogrim/technion-sogrim#121]
maybe we need to think about the "location" of this logic - fe / be?
@liadaram1  @benny-n  wdyt?

_Originally posted by @NissanOhana in https://github.com/sogrim/technion-sogrim/issues/120#issuecomment-1073310232_

**Comment by liadaram1** [comment]
@NissanOhana 
Why would we want this logic in the be? Is it beneficial? 
In the fe we already have all the data we need, don't we?

**Comment by benny-n** [comment]
Decision: Negligible size of component - keeping in FE
