### ISSUE TITLE
Possible synchronization issue between B.O. app and Students app 

### ISSUE THREAD

**Issue by benny-n** [sogrim/technion-sogrim#29]
We should consider this possible scenario and decide how to solve it:

1. Some users use the Student app with catalog A and their UserDetails are saved to the DB.
2. One of the coordinators (רכזות) updates catalog A and changes its demands and rules.
3. All of the users who use catalog A now have invalid details.

**Comment by NissanOhana** [comment]
solution:
1. after mazkira updates the DB, run all users.
2. in each user that the relevant catalog changed, update `modified = true`
3. hola!

**Comment by benny-n** [comment]
Simpler solution: don't allow editing catalogs after they are created
