### ISSUE TITLE
Support "in progress" courses

### ISSUE THREAD

**Issue by benny-n** [sogrim/technion-sogrim#89]
- [x] add "settings" to ```User``` resource 
  - [x] ~~add 'modified' flag to settings~~ (cancelled)
  - [x] add compute_in_progress flag as a setting
  - [x] update db
- [x] create ```PUT /student/settings```
- [x] before degree-status compute, check compute_in_progress flag and change courses statuses if needed.
- [x] add toggle button UI to client 
- [x] change default course_status from 'complete' to 'in-progress'

**Comment by idanfi** [comment]
It would be great if the "in progress" courses could extend to future semesters as well, so you could use this tool to program the rest of your title. 
Lets say I'm going to start semester 5, so I'd like to know that my future plans make sense.

**Comment by benny-n** [comment]
@idanfi  that's the plan. :slightly_smiling_face:
btw, you can already simulate this behavior (although not as comfortably as it would be in a fully implemented feature) right now! create some semesters, add courses to them, and click "סגור את התואר".

**Comment by idanfi** [comment]
I think the courses must have passing grade in order to be part of the calculation, which could be a bit annoying, but that's better than nothing :)

**Comment by benny-n** [comment]
closed by #125
